events {} #Bloc obligatoire, même vide Sert à configurer - nombre de connexions simultanées , modèle d’événements (epoll, etc.)

http { #config HTTP
    server { #definition serveur web
        #server_name monsite.fr; #non utile dans notre cas, mais permet de faire du routin par domaine
        listen 80; #port d'ecoute

        location / { #definition du comportement pour toute les routes
            proxy_pass http://flask:5000; #redirection des requêtes http://nomservicedocker(docker-compose):portappflask
            
            proxy_set_header Host $host; #Transmets à Flask le nom du site demandé par le client
            proxy_set_header X-Real-IP $remote_addr; #Transmets l’IP réelle du client
            #les 2 lignes au dessus permette d'éviter la perte d'info du client sur le site demandé et son ip en passant par le serveur nginx
            #ligne bonus: proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; #permet de conserver la chaine d'ip compléte si on passe par plusieurs proxies
        }
    }
}